#!/bin/bash
#BSUB -J petsc-test
#BSUB -q ser
#BSUB -n 10
#BSUB -m 'r01n23'
#BSUB -e log.out
#BSUB -o log.out

module purge
module load intel/2018.4
module load mpi/intel/2018.4

mpirun -np 10 ./main.out -n 100000 \
  -ksp_type gmres \
  -pc_type asm \
  -ksp_monitor_short \
  -ksp_converged_reason \
  -log_view > result.log 2>&1