#!/bin/bash
#BSUB -J petsc-test
#BSUB -q ser
#BSUB -n 10
#BSUB -m 'r01n13'
#BSUB -e petsc.err
#BSUB -o petsc.out

module purge
module load intel/2018.4
module load mpi/intel/2018.4

mpirun -np 5 ./main.out -n 20 \
  -ksp_type gmres \
  -pc_type asm \
  -ksp_monitor_short \
  -ksp_converged_reason \
  -ksp_view \
  -log_view > result.log 2>&1