#!/bin/bash
#BSUB -J petsc-test
#BSUB -q ser
#BSUB -n 10
#BSUB -e log.out
#BSUB -o log.out

module purge
module load intel/2018.4
module load mpi/intel/2018.4

mpirun -np 10 ../main.out -n 100 \
  -ksp_type gmres \
  -pc_type asm \
  -log_view > result_1.log 2>&1

mpirun -np 10 ../main.out -n 1000 \
  -ksp_type gmres \
  -pc_type asm \
  -log_view > result_2.log 2>&1
